name: Terraform CD

on:
  workflow_run:
    workflows: ["Terraform CI"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set S3 bucket name
      env:
        TERRAFORM_BUCKET_NAME: ${{ vars.TERRAFORM_BUCKET_NAME }}
      run: |
        sed -i 's|${TERRAFORM_BUCKET_NAME}|'"$TERRAFORM_BUCKET_NAME"'|g' provider.tf

    - name: Download Plan
      uses: actions/download-artifact@v2
      with:
        name: terraform-plan
        path: plan.tfplan

    - name: Terraform Apply
      run: terraform apply plan.tfplan

    - name: Notify deployment success
      run: echo "Deployment successful!"
