name: Terraform CD

on:
  workflow_run:
    workflows: ["Terraform CI"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Download Plan
      uses: actions/download-artifact@v2
      with:
        name: terraform-plan
        path: plan.tfplan

    - name: Terraform Apply
      run: terraform apply plan.tfplan

    - name: Notify deployment success
      run: echo "Deployment successful!"
